### ISSUE TITLE
Missing concept lists

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#10]
Currently we have metadata on 58 concept lists in `conceptlists.tsv` but only 50 concept lists in `conceptlists/`. The missing ones are

- Kassian-2010-110
- Gabelentz-1891-120
- Snider-2004-1700
- Zorc-1974-100
- Shevoroshkin-1991-23
- Swadesh-1960-100
- Marsden-1782-50
- Pallas-1785-441

We should either add these - maybe even as empty stubs - or remove them from `conceptlists.tsv`, I think. In case we add empty concept list files for these, we might need a flag signaling the process status in `conceptlists.tsv`, to prevent them from being imported in the concepticon app.

**Comment by LinguList** [comment]
Empty stubs would be preferred by me, since it is planned to get these included quickly, at least the short ones. It is even possible that parts were already done, but that I forgot to move them. I'll try to have the missing stuff added before the Leipzig conference. Let's leave this issue open until it's done and work with stubs in the meantime, if that's OK?

**Comment by xrotwang** [comment]
If they get added quickly, I'll just keep the workaround in the concepticon import script I already have: Only import concept lists which have not only metadata.

**Comment by LinguList** [comment]
allright, I'll try to get them added as quickly as possible (with Snider, I am not sure though, since it is a very large list), so we could as well store the currently unmapped meta-data-lines along with the currently unmapped but already digitized lists (and there would be not specific pressure or workarounds, and whenever a new list is added, we need to add the meta-data).

**Comment by LinguList** [comment]
Recapitulating now, which lists are still missing:

*    Kassian-2010-110
*    Snider-2004-1700
*  Pallas-1785-441
The Kassian-list is more or less straight-forward, the other lists are, however, complicated since very long, but we'll look into that.

**Comment by LinguList** [comment]
Update: kassian has now been added, snider is still pending, the same holds for pallas, which needs to be translated to english first (started to work on that).

Missing:

* Snider-2004-1700
* Pallas-1785-441

**Comment by LinguList** [comment]
we should assess the feasibility to have these done before the next release.

**Comment by LinguList** [comment]
I'm working on Pallas. 250 concepts still left to be translated. But here a general questions: how should we handle inflected forms? Should we just link them to the same base concept for the moment? Adding extra concept sets for these cases seems to be something like an overkill, and we have enough to work on already with the normal concepts.

**Comment by xrotwang** [comment]
From my layman's perspective, linking to the base concept seems appropriate. We want a concept list after all, and not a comparative dictionary.

**Comment by xrotwang** [comment]
Has been split into two issues for the remaining missing concept lists.
