### ISSUE TITLE
Provide mapping to glottolog in language data?

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#117]
We provide translations for concpet sets in about 10 maybe more languages for now. Ideally, we would list these, include them in tests (making sure we use the same name always), and then also link them to glottolog, so that it's clear which language we mean.

**Comment by xrotwang** [comment]
So I guess the most transparent way to do this would be using glottocodes instead of language names in `conceptlists.tsv` and as header in the individual concept lists? Alternatively, there could be an explicit mapping between per-list names and glottocodes - maybe we should add `conceptlists/<cl-id>.tsv-metadata.json` files, describing the columns in the concept list? This may also be a place to add arbitrary/custom metadata per conceptlist?

**Comment by xrotwang** [comment]
OTOH: In the light of the data presented in #100, it looks like for the moment we could get away with simply adding an explicit mapping of language names to glottocodes - say in `pyconcepticon/data.py`. If we make sure to look at the list of custom attributes periodically, there shouldn't be too much risc of things getting ugly quick.

**Comment by LinguList** [comment]
Okay, this sounds like a good idea, and we try to maintain language names consistently in the columns anyway, as one can also see from the columns. For the multi-lingual mapping (which still works badly, but mostly due to coverage problems), it is definitely useful to keep track on which languages we have, as we could then also expand at some point, and some people have been explicitly asking for the possibility to have the glosses in other languages to use them for their own questionnaires.
