### ISSUE TITLE
Source PDF for Sato 2002 looks weird

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#137]

**Comment by LinguList** [comment]
Maybe we should explicate this, but this is a wanted feature:

* since I am not sure regarding the copyright, I decided to cut of those
pieces which we digitize in the end in our lists, so that people can
compare original with our version.

This means, since Sato consists of a very long text listing not only the
concepts but also much more, that I would often just pick the relevant
parts and collect it in a PDF.

You find this also in Struve2014 and other sources.
