### ISSUE TITLE
Concepticon Links to external resources

### ISSUE THREAD

**Issue by BettinaKlimek** [clld/concepticon-data#147]
In the paper "Concepticon: A Resource for the Linking of Concept Lists" it is mentioned that:

> We do not have full coverage for each of the resources, partially
> due to lacking data, partially since we have not yet had time to
> link all data. Our current coverage is: WordNet53%,OmegaWiki
> 79%, BabelNet 35%, SimLex-999 18%, MRC 74%, and EAT
> 78%.

Where can I the datasets containing these links of the current coverage?

**Comment by LinguList** [comment]
sorry, this is probably not very transparent:

* each concept set will have a little window to the right showing all external links, if there are, so if you click on a concrete concept set (like from the [parameters](http://concepticon.clld.org/parameters)), you find all we have for this very concept set to the right, e.g., for [contemptible](http://concepticon.clld.org/parameters/1), we have AOA, Babelnet, MRC, and OmegaWiki.

In github, which is more important for resource people, the relevant information is in this folder:

* https://github.com/clld/concepticon-data/tree/master/concepticondata/concept_set_meta

potentially we should think of adding this explanation to the [contributing.md](https://github.com/clld/concepticon-data/blob/master/CONTRIBUTING.md), since it is not necessarily obvious, how one would contribute new meta-data (although this would be as cool as new concept sets).

I'm renaming this issue to that very topic: enhance contribution information, and we should also add links in the readme.md file, where all folders and files are given, which makes it just easier to navigate through it.
