### ISSUE TITLE
We have the concept set "betel nut" twice

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#216]
There's

```
217     BETELNUT        Agriculture and vegetation      The seed of the areca palm (Areca catechu).
```

and

```
2369    BETEL NUT       Food and drink   The seed of the areca palm (Mama'an in Meranau common version).
```

**Comment by xrotwang** [comment]
Hm. I just realized these two are related with a `sameAs` relation, and the latter isn't linked from any concept. So was this our mechanism to deal with duplicates - i.e. unlink one and relate it via `sameAs` to the other? If so, this should be marked in `concepticon.tsv` as well, I'd say. Or actually, be marked only there - say with a flag `duplicate` or `invalid`.

**Comment by xrotwang** [comment]
Thinking a bit more about it, this may be a suitable device to increase auto-mapping accuracy, e.g. by providing synonym glosses for concepts like "WE (INCLUSIVE)". But if we do this, this must be very transparent **and** the API must make it easy to deal with de-duplicated concept sets.

**Comment by LinguList** [comment]
well, my rerefine.py was handling this: search for same-asses, and only link the first in order of ID. Basically, all those sameas-things could be kicked out, but I left them there also for mapping purpose (as it is the spelling that will help in getting a better mapping, like an alias), and since I did not want to have none-IDs. Should've mentioned this earlier. A rerefine-function might now be good for the api, as this also checks that all glosses have the right concept set id, and vice verse.
