### ISSUE TITLE
Bird terminology in cross-linguistic perspective

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#281]
Just stumbled over this article in a strange new journal:

* http://www.mdpi.com/2226-471X/1/2/12/htm

They propose bird terminology, link it to some scientific data, and search for names in different languages. Given that @SimonGreenhill  recently introduced a bird kind we found in a word list, this may be an occasion to introduce more, as it is also a language resource (offers bird names in 6 languages). 

In general, this also brings us to the discussion of where we hope to be able to go with CLLD Concepticon: we can surely improve in many respects, but do we have a principal limit in what we include semantically, or do we say: we grow as much as available word lists out there offer us new concepts? 

And do we consider to add new relations in these cases, as clearly, the word "bird" is not broader than "duck", but we would like to annotate that they donate in some way similar things.

**Comment by xrotwang** [comment]
Regarding relations: I think Concepticon is not the place to mirror biological taxonomies; having metadata like a mapping to EOL is all that's needed to figure out the relation among species. Hierarchical semantic categories could be handled in a similar way - provided we find appropriate metadata available somewhere.

Regarding scope of Concepticon in general, I'd say that we should keep the focus on pragmatism, i.e. Concepticon should be a tool to make lexical data comparable. Since lexibank sets out to become the main resource for lexical data, we should grow Concepticon mainly driven by lexibank needs. I see this as similar to software development, where it is often tempting to grow features, even if these are not-yet-needed. Often such features turn out to be ill-conceived, and have to be refactored upon first actual use case.

**Comment by xrotwang** [comment]
So regarding this bird paper, I'd say the data should - at least at the moment - be rather integrated into Tsammalex.

**Comment by LinguList** [comment]
absolutely fine with me. Can we port the issue, so that you don't forget
it in Tsammalex context? Afterwards, we could link from here and close
the issue in concepticon, reopening it if we feel the need for it.

**Comment by xrotwang** [comment]
See related issue in tsammalex https://github.com/clld/tsammalex-data/issues/19
