### ISSUE TITLE
pip install should be useful, or not recommended

### ISSUE THREAD

**Issue by Anaphory** [clld/concepticon-data#374]
The readme says

> `pyconcepticon` can be installed from PyPI, e.g. using pip
>
>     pip install pyconcepticon

However, that installation does not come with any data (and assumes it can find its data in something like `PosixPath('/home/anaphory/.local/lib/python3.5/site-packages')`). It would be nice if the lazy user was not provided with useless way to install things – I think either the pip installation should pull in data or not be that easily available at all.

**Comment by xrotwang** [comment]
Well, having about 30 virtualenvs on my machine, most of them with
pyconcepticon installed, I really appreciate that it does not come with all
the data.

Am 21.09.2017 14:38 schrieb "Gereon Kaiping" <notifications@github.com>:

**Comment by xrotwang** [comment]
Maybe this info should be de-emphasized, recommending installation via `python setup.py develop` from a clone or export of the repository. Making the package available on PyPI, though, and without the data, makes my life a lot easier.

**Comment by Anaphory** [comment]
Yes, I'm mostly suggesting de-emphasizing that way of installation.

Your use case makes a lot of sense, but maybe there is a compromise: I'm still not firm in writing `setup.py`s, but maybe that script could be made to download (and possibly update) the data once into a canonical location shared between all `pyconcepticon`s in all virualenvs, setting the root path appropriately, with a command line switch for “don't bother with data”, “download data to a path relative to this install” and “check and possibly download data to the following path”? 

Or with the second one being the default, as it is currently, and the first one being an easy CLI switch, if you think that's a lot better.

**Comment by LinguList** [comment]
I have switched to complet setup.py installations now, as it is easier with virtualenvs, and updating to pypi is also annoying (but maybe because I don't know how to do this manually), so I'd say: deemphasizing first is probably enough. A problem of pypi and pure installs, as I know from lingpy, is also to write these extra information of what data needs to be transferred (the manifest file). I was always messing it up with lingpy, and adding this to concepticon will also be a bit of a thing that seems like more work than asking to install via setup.py develop (?).

**Comment by xrotwang** [comment]
Doing any extra work in `setup.py` is error-prone, as it may execute in environments you didn't have in mind - or can't really test (other platforms, travis, etc.). Downloading data during install will also make continuous integration with travis slower - and more fragile. I also want to make users aware that the data lives in a git repository - which they could even contribute to! This would be partly defeated by putting the data automatically into "default" locations - because as far as I'm aware, there are no cross-platform default data locations which are also well known and accepted by users.

So, yes, we should de-emphasize the install option via PyPI, but otherwise I think there are good reasons for things to be the way they are.
