### ISSUE TITLE
Is --map_type= (as referenced in CONTRIBUTING.md) still in use? 

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#398]
After successfully pushing to master without the slightest intention of doing so, here something hopefully more constructive: The guide for making [contributions using automatic mapping](https://github.com/clld/concepticon-data/blob/master/CONTRIBUTING.md#using-automatic-mapping-software) refers to an argument (`--map_type`) for `map_concepts` that, as far as I can see, doesn't exist (anymore)

**Comment by LinguList** [comment]
it should still be there, but we now almost exclusively switched to the faster map2 rather than the older map1. In my opinion, we could even delete map1 (you'll find it via the CLI code, there are two mapping algorithms), but I'd prefer to have this done along with a refinement of the glosses.py as addressed in #382

**Comment by LinguList** [comment]
I suppose, but I am open for a discussion, also with @tresoldi, that we reduce the current mapping algorithm in concepticon to the one that we currently have, provided that we refine the different degrees of similarity, and potentially by also adding some of the ideas that wen't into the online look up #403. That would allow us to close this immediately, once the new algorithm is provided.

**Comment by tresoldi** [comment]
It seems the function is there (it is `glosses.py:concept_map()`, right? opposed to `concept_map2()`) but @chrzyki is right, the command line argument is not there (I wanted to use it).

I think what is important is for those who know Concepticon better to decide/guide on the resources and eventual dependencies the mapping can/should use. As for the algorithm, from my short experience the problems in general are (somewhat in decreasing order of work involved):

- confusing (or even erroneous) glosses in the source, for which the algorithm should either suggest the most common concept or a list of concepts (e.g., `fly`, by itself, without specifying if it is the animal or the action)
- glosses that map to concepts in Concepticon but involving more than a `grep` to be found (e.g. `eggplant` for `AUBERGINE`, when it is possible to find using the description for the concept, or `pigeon` for `DOVE`, when you actually have to think that it might be classified differently and have to look for the scientific name)
- glosses that seem to map to one of the concepts already there, but which are actually partial matches or false positives (e.g., for Sun's list one of the `earth` labels, which seems to be neither earth as soil, as land, or even as planet, but earth as "not heaven")
- detailed glosses, for example with part-of-speech information, that don't map directly but make it easier to find out what it is about (e.g., glosses like `fly (n)` and `fly (v)`)

**Comment by LinguList** [comment]
This all can be handled by improving on the similarity_level. This is the reason why one concept may be preferred over another concept, and this can be easily handed by adjusting what counts to be how similar in the current concept_map() algo. The detailed glosses may indeed be useful for those who are new to concepticon, so we could just add additional info later on when making the automatic linking. My dream would be to have a small HTML/JS thingy that is created for a concept list and allows the users to select data by clicking it, and then download using HTML-5 filewrite API, but that's not milestone 1.1. For this I think we should probably consider:

- [ ] add definition, if user wishes so
- [ ] add POS information (derived from ontological categories)
- [ ] refine similarity levels
- [ ] add disturbed input into the Gloss() class, so that a gloss has a representation that lacks a letter or similar, which will result in a different similarity level

I guess, with this, we'll be fine. The eggplant/aubergine cases are already covered, as we use our linked data to compare. And we also need to leave some work to the people who actually link a concept.

**Comment by chrzyki** [comment]
I've updated the documentation to the current version of the command for automated mapping. Should the other tasks be split into separate issues? I could go ahead and do that.

**Comment by LinguList** [comment]
Yes, please, good idea!

**Comment by chrzyki** [comment]
Documentation updated. Enhanced concept mapping outlined in #422.
