### ISSUE TITLE
Documentation of Relation Mapping

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#411]
Hey,

I could only find the set of relations that are to be used with Concepticon directly [in the code](https://github.com/clld/concepticon-data/blob/f476c61ba1f9ef733584defff3b8e0fb15323ff6/helpers/relations.py) (if it is also documented someplace else I haven't found it yet, sorry!).

It might be useful and helpful for new contributors to list those directly in the CONTRIBUTING.md, together with a short comment on how each relation is to be used.

**Comment by xrotwang** [comment]
Good find! Yes, we should document these. We may actually start a Concepticon relation ontology, which could be very lightweight - considering that we mostly re-use well-defined relations like [skos:broader](https://www.w3.org/2009/08/skos-reference/skos.html#broader).

Any takers?

**Comment by LinguList** [comment]
Yes, and this would be a good chance to evaluate one specific requirement I consider useful: we should restrict the edges between concepts in the graph to the immediate neighbor, e.g., having a graph (here shown in triples):

Source | Target | Relation
--- | --- | ---
grandfather | grandparent | narrower
grandfather (father's father) | grandparent | narrower
grandfather (father's father) | grandfather | narrower

we should reduce the edges to:

Source | Target | Relation
--- | --- | ---
grandfather | grandparent | narrower
grandfather (father's father) | grandfather | narrower

since the relation between ```grandfather (father's father)``` and ```grandparent``` is derivable from the relation between ```grandfather``` and the others. I don't know how complex it is to compute this, but it would help us to keep the number of relations small.

**Comment by LinguList** [comment]
BTW: I can look into the network algo for reducing/checking relations, but I can't take over the ontology, as I don't know the principle behind this (I don't even know what an ontology is).

**Comment by chrzyki** [comment]
If I understand you correctly that should be a fairly straightforward case of transitive reduction in a graph, which has a reasonable (read: for our purpose not relevant) complexity/timing impact.

**Comment by LinguList** [comment]
Yes, that sounds like what I mean. We'd only need it for testing, I suppose, so we could even use networkx as dependency for tests. It would be useful, also with respect to the ontology, right?

**Comment by chrzyki** [comment]
Should we split this into two separate issues/tasks?

- documentation of relations in Concepticon and how to use/find/apply them
- transitive reduction for reducing 'irrelevant' relations

**Comment by LinguList** [comment]
Yes, please do so!

**Comment by chrzyki** [comment]
Done, will be tracked in #419 and #420 respectively.
