### ISSUE TITLE
Number Concepts

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#526]
In preparation for linking the Numerals Concepts, we'd need to have more number concepts in Concepticon (probably in the magnitude of 100-150 additional concepts; I could calculate the exact number if required).

- Would it be 'okay' to plainly add more numerical concepts along the same vein as the existing ones? I could prepare a PR.
- Should we unify the definitions for the existing number concepts? Some specify cardinality, some relatedness to Arabic numbers, etc.
- Finally, is it fruitful to have that many additional concepts that are probably rarely used? It seems kind of futile, but I can't think of any other way.

**Comment by LinguList** [comment]
I think it is not hurting, as long as the glosses are chosen in such a way that our current mapping algorithm does not spit "one million and one" etc. if you look for one, but since we only split on comma, this won't happen anyway. But I'd say: a) include in our metadata (we already have it), and b) maybe check links to wikipedia (could be automated), as this may just help us to get a bit more metadata for these concepts...

**Comment by LinguList** [comment]
And you could also regularize the number system, e.g., by saying that the diefinition is just:

> The number 1.

We don't need more info that that, I'd say.

**Comment by chrzyki** [comment]
Awesome, thanks for the input!

**Comment by chrzyki** [comment]
:+1: for simple definitions in combination with automated links/metadata to/from Wikipedia, e.g. https://en.wikipedia.org/wiki/16_(number).

**Comment by xrotwang** [comment]
I guess "The number X." is good, "natural number" would be good as well.
