### ISSUE TITLE
Typo: rain

### ISSUE THREAD

**Issue by pavelsof** [clld/concepticon-data#76]
Hello from Tübingen!

First of all, thank you all for building and maintaining this project!

Here are a couple of typos that I found in the concept names:

* RAIN (PRECIPATION) --> RAIN (PRECIPITATION)  // ID: 658
* FRONT TOOTH (INEISOR_ --> FRONT TOOTH (INCISOR)  // ID: 442

The latter has been fixed here in the repo, but apparently the fix has not reached the web server.

Kind regards,
Pavel

**Comment by LinguList** [comment]
Thanks a lot, Pavel! If it has been fixed in the repo, that means, it
will be fixed in the next update (we update the online repo only once a
year to keep it as our stable version that people can use). But the
precipitation is one thing we'll definitely need to update and I'll do
so right now. Note that it will have to wait until I make the next major
Pull Request from my local copy to the official repo, but I'll
immediately change it.

Thanks again!
